services:
  web:
    image: ghcr.io/changpopwiki/premiere-relay-archive/web:latest
    expose:
      - "9000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  scheduler:
    image: ghcr.io/changpopwiki/premiere-relay-archive/scheduler:latest
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/app/data
    networks:
      chp_proxy:
        aliases:
          - premiere-relay-archive
      default:

networks:
  chp_proxy:
    external: true